source 'http://rubygems.org'

gem 'redis-caches', :git=>"git://github.com/CalculatedContent/redis-caches.git"
gem 'sourcify', :git=>"git://github.com/CalculatedContent/sourcify.git" 
gem 'qless', :git=>"git://github.com/CalculatedContent/qless.git"

# helper scripts
gem 'whenever'
gem 'fog'
gem 'headless'
gem 'selenium-webdriver'

gemspec
